// Images
export { default as background } from './img/background.jpg';
export { default as backgroundFormules } from './img/background_formules.jpg';
export { default as default_img } from './img/default_img.jpg';
export { default as khayat_flan } from './img/khayat_flan.jpg';
export { default as logo } from './img/logo.png';
export { default as notfound } from './img/notfound.gif';
export { default as NOVA1 } from './img/NOVA1.png';
export { default as NOVA2 } from './img/NOVA2.png';
export { default as NOVA3 } from './img/NOVA3.png';
export { default as NOVA4 } from './img/NOVA4.png';
export { default as NOVANULL } from './img/NOVANULL.png';

// Icons
export { IconArrowRight } from './svg/IconArrowRight';
export { IconBurger } from './svg/IconBurger';
export { IconCalcul } from './svg/IconCalcul';
export { IconClose } from './svg/IconClose';
export { IconCrown } from './svg/IconCrown';
export { IconCrownOutlined } from './svg/IconCrownOutlined';
export { IconDark } from './svg/IconDark';
export { IconDepense } from './svg/IconDepense';
export { IconDetails } from './svg/IconDetails';
export { IconDrink } from './svg/IconDrink';
export { IconEnergie } from './svg/IconEnergie';
export { IconError } from './svg/IconError';
export { IconFemale } from './svg/IconFemale';
export { IconFilter } from './svg/IconFilter';
export { IconFood } from './svg/IconFood';
export { IconFormula } from './svg/IconFormula';
export { IconHome } from './svg/IconHome';
export { IconIdea } from './svg/IconIdea';
export { IconInfo } from './svg/IconInfo';
export { IconIntolerance } from './svg/IconIntolerance';
export { IconKhayat } from './svg/IconKhayat';
export { IconLight } from './svg/IconLight';
export { IconLoader } from './svg/IconLoader';
export { IconLogin } from './svg/IconLogin';
export { IconLogo } from './svg/IconLogo';
export { IconMail } from './svg/IconMail';
export { IconMale } from './svg/IconMale';
export { IconNotification } from './svg/IconNotification';
export { IconNutriScoreA } from './svg/IconNutriScoreA';
export { IconNutriScoreB } from './svg/IconNutriScoreB';
export { IconNutriScoreC } from './svg/IconNutriScoreC';
export { IconNutriScoreD } from './svg/IconNutriScoreD';
export { IconNutriScoreE } from './svg/IconNutriScoreE';
export { IconNutriScoreNull } from './svg/IconNutriScoreNull';
export { IconOnOff } from './svg/IconOnOff';
export { IconParameter } from './svg/IconParameter';
export { IconPDF } from './svg/IconPDF';
export { IconPhone } from './svg/IconPhone';
export { IconPortion } from './svg/IconPortion';
export { IconReset } from './svg/IconReset';
export { IconScan } from './svg/IconScan';
export { IconSearch } from './svg/IconSearch';
export { IconSidebarClose } from './svg/IconSidebarClose';
export { IconSidebarOpen } from './svg/IconSidebarOpen';
export { IconSuccess } from './svg/IconSuccess';
export { IconTemplate } from './svg/IconTemplate';
export { IconThumbKO } from './svg/IconThumbKO';
export { IconThumbOK } from './svg/IconThumbOK';
export { IconTrash } from './svg/IconTrash';
export { IconUser } from './svg/IconUser';
export { IconWarning } from './svg/IconWarning';
